### ISSUE TITLE
Language translation for lang="*" attributes in tags not working

### ISSUE THREAD

**Issue by cosmopolit** [Irrelon/jquery-lang-js#102]
After updating JQuery from 2.2.4 to 3.2.1 the translation in html is not working anylonger. Translation with javascript is working as before. 

Any hints to solve this issue?

**Comment by Irrelon** [comment]
Hey ya, I've not tested newer jQuery versions. If you find out what causes it can you let me know?

I so rarely use jQuery anymore that I didn't even know there was a version 3. Been using AngularJS for ages now. :)

**Comment by curunoir** [comment]
Still not working with Jquery 3.2.1 with either inline or javascript change methods. No errors in the console. In the network console language packs does not seem to be loaded.

**Comment by Irrelon** [comment]
@curunoir Are you able to place some breakpoints and see where it is failing?

**Comment by curunoir** [comment]
Nevermind it's working now. I guess I was confused when using same lang tags on init method and html tags.

**Comment by Irrelon** [comment]
Cool so working with jQuery 3. Will close this issue then.
