### ISSUE TITLE
Cannot set property 'langToken' of undefined

### ISSUE THREAD

**Issue by uoiszero** [Irrelon/jquery-lang-js#103]
at line 299, when node type is 3, nodes length will longer then nodeObjArray length.
so

`if(nodeObjArray.length === 1){`
`    nodeObjArray[0].langToken = elem.data('langToken');`
`}`

maybe better

**Comment by Irrelon** [comment]
Hi ya,

Could you put together a pull request for this change? That way you will be properly credited with the fix.

Thanks,

Rob
