### ISSUE TITLE
Will support Zepto compatible implementation？ 

### ISSUE THREAD

**Issue by jianhua1982** [Irrelon/jquery-lang-js#105]
Hey guys; 

It works with jQuery very well,  any  idea on Zepto compatible implementation? 
Experience: 
Dues to jQuery & Zepto difference, need some work force to fix them.  

Thanks

**Comment by Irrelon** [comment]
Hi ya,

I have not tested against zepto but I suspect it will not work because of the reduced functionality zepto intentionally provides.
