### ISSUE TITLE
Translating inline elements

### ISSUE THREAD

**Issue by TamaraJug** [Irrelon/jquery-lang-js#106]
Hello!
Please help.. I can't seem to find a solution.
How should I translate this example:
`<p>This is <strong>highlighted part</strong> of text.
`

I tried:
`<p lang="en">This is <strong>highlighted part</strong> of text.` 
`<p lang="en">This is <strong lang="en">highlighted part</strong> of text.`

Not working. Please help. Thank you!!

**Comment by sheghzo** [comment]
just remove <strong> tag,it should work!

**Comment by Irrelon** [comment]
you need to wrap your text sections in a span tag:

<p><span  lang="en">This is</span> <strong lang="en">highlighted part</strong> <span  lang="en">of text</span>.
