### ISSUE TITLE
released version 3.0.0 unstable

### ISSUE THREAD

**Issue by keithbox** [Irrelon/jquery-lang-js#109]
Your released version 3.0.0
unable to switch the language via "data-lang-token", the problem solved when I try the master branch.

**Comment by Irrelon** [comment]
Are you able to see why / put in a PR to fix?

**Comment by Irrelon** [comment]
Closing as no further information was provided

**Comment by keithbox** [comment]
I found the reason, it is because a <br> tag exist in my element
