### ISSUE TITLE
Parametric text translate

### ISSUE THREAD

**Issue by anilaynaci** [Irrelon/jquery-lang-js#121]
How can we translate parametric text?

For example;
EN: Pay %s
TR: %s Öde

**Comment by Irrelon** [comment]
Hey there, this library is designed as a token replacement tool rather than a template parser so you are not able to do that with this library directly.

If you are trying to do as above you are much better off ditching jQuery completely and using a modern template rendering framework like React.

**Comment by Irrelon** [comment]
The new version 4.0.0 of the library that I updated today includes this new feature: https://github.com/Irrelon/jquery-lang-js#dynamic-data--template-strings
