### ISSUE TITLE
Langpack jquery version issue. We have to use jquery 3.x!

### ISSUE THREAD

**Issue by enovator** [Irrelon/jquery-lang-js#122]
Hi, 

First of all thank you for your great work!
Now the problem! :-)

Can we use this awesome plugin with jquery 3.x ?
We use BootStrap 4, which uses JQuery 3.3.1. The Langpack plugin needs jquery 1.x.
What should we do?

Thanks!

**Comment by Irrelon** [comment]
Hi ya,

Have you tested on jQuery 3.x? If so, what happened / errors / feedback etc?

**Comment by Irrelon** [comment]
@kristofzerbe Hey, thanks for the info, can you describe in more detail?

**Comment by Irrelon** [comment]
@kristofzerbe Thanks for making the PR to fix this! https://github.com/Irrelon/jquery-lang-js/pull/126

**Comment by RavenWits** [comment]
Hi there having this error with JQuery v3.6.0!

![Error](https://user-images.githubusercontent.com/63670898/116421700-c1a6a380-a847-11eb-901e-396abef0f482.jpg)
