### ISSUE TITLE
Uncaught ReferenceError: Lang is not defined

### ISSUE THREAD

**Issue by Shokhrukh2606** [Irrelon/jquery-lang-js#124]

**Comment by Irrelon** [comment]
Hi, can you provide any information?

**Comment by Shokhrukh2606** [comment]
i have some questions regarding to your repo. Is it for statically changing content of lang of my browser app

Отправлено с iPhone

**Comment by Irrelon** [comment]
> i have some questions regarding to your repo. Is it for statically changing content of lang of my browser app Отправлено с iPhone
> […](#)
> 6 апр. 2020 г., в 21:06, Rob Evans ***@***.***> написал(а): Hi, can you provide any information? — 

This plugin is only for web sites or web applications that use jQuery. It can change the content language of any web application but if the application is built using a modern framework such as React Native, you should not use jQuery to modify the DOM.

What framework is your browser app built with? Do you already use jQuery or are you using a more modern framework like React Native?

**Comment by Irrelon** [comment]
Closed with no response
