### ISSUE TITLE
How to translate dynamic alert content

### ISSUE THREAD

**Issue by dianeryanto** [Irrelon/jquery-lang-js#125]
Hi Sir, thanks for your great work it's really help.

But i found some problem, i don't know how to translate dynamic alert content.
Already read your documentation, you suggest using `window.lang.translate` for alert, but it for static content. 

Example for dynamic alert content `alert("Are you sure to delete "+name+" product");`

Any idea for solve this problem?

Thanks before Sir.

**Comment by Irrelon** [comment]
Hi there!

I've just made a large update to do what you need. Please see the readme file on "template strings": https://github.com/Irrelon/jquery-lang-js#dynamic-data--template-strings

This new version is the first large update for a long time and I don't think I broke anything but let me know if you have any issues.

**Comment by Irrelon** [comment]
P.S. you will need to update to version 4.0.0 in order to use this new feature.

**Comment by Irrelon** [comment]
Closing as this has now been resolved ;)

**Comment by dianeryanto** [comment]
Awww, i dont think you'll response me but you just made new update for my needs.

Really big thanks Sir! 👍

**Comment by dianeryanto** [comment]
Sorry Sir, i think i have some new issue.

Based on your example, we must define token like this, and it works.

> `"token": {
>         "myTranslationToken":"Hello ${data.firstName} ${data.lastName}"
>      }`
> 
> `alert(window.lang.translate("myTranslationToken", "en", {"firstName: "Amelia", "lastName": "Earhart"}));`
> 
> Result : `Hello Amelia Earhart`

The problem is how to create dynamic default language too? In html tag we define like this
> `"token": {
>         "myTranslationToken":"Hello ${data.firstName} ${data.lastName}"
>      }`
`<div lang="id">Default Language</div>`

**Comment by Irrelon** [comment]
Hey ya! No problem to ask questions! If I have time I will always try to help. 

You can create a language json file for your default language and load it the same way you load the other languages. 

If your default language is “id” and your second language is “en” then you world create two json files, one called “id.json” and one called “en.json” and then both will have the token “myTranslationToken” with their respective value “halo ...” and “hello...”

Does that make sense? I’m replying from my phone at the moment so I can’t insert code examples but the readme.md was updated and includes an example :)

Please let me know if that helps you :)

**Comment by dianeryanto** [comment]
Already try your suggest to create 2 different json `id.json` and `en.json` and both of them have token `myTranslationToken` with different language.

>Load the json
>var lang = new Lang();
> lang.dynamic('en', '/plugin/jquery-lang-js-master/js/langpack/en.json');
> lang.dynamic('id', '/plugin/jquery-lang-js-master/js/langpack/id.json');
>lang.init({ defaultLang: 'id'})`

But when i try to change language to `en -> id` or `id -> en`,  
The output still in one language, not dynamically change. 

my alert like this 
`alert(window.lang.translate("myTranslationToken", "id", [value1, value2]));`

Am i wrong or miss something?

**Comment by dianeryanto** [comment]
Sir, i think i got trick for solve my problem but i think not best solution.

i create `actual_lang` variable who dynamically change based on what languages we choose and put it on on second parameter.

Like this and working perfectly.
`alert(window.lang.translate("myTranslationToken", actual_lang, [value1, value2]));`

So i think i can close my problem.
Thanks for your help sir.

**Comment by Irrelon** [comment]
Hey! I'm at my computer now.

I fully understand what your problem is now! :)

So for the translate() method you needed to be able to "fill in" the current selected language.

This is very simple. Just pass undefined as the second parameter :)

e.g.

```js
alert(window.lang.translate("myTranslationToken", undefined, [value1, value2]));
```

**Comment by dianeryanto** [comment]
Yes, already try using `undefined` or get the actual language from cookies and both of them working perfectly.
But i prefer using `undefined` based on your suggest as project owner 😄 

Thanks for your help sir !
