### ISSUE TITLE
Using with Wordpress Plugin Bogo requirements

### ISSUE THREAD

**Issue by tomasts248** [Irrelon/jquery-lang-js#135]
May I ask if there's a way to use Lang-js with Bogo Wordpress plugin which I am currently testing for translating content with Wordpress. Here's the link : https://wordpress.org/plugins/bogo/ 
This plugin uses this url format for non default languages: www.website.com/en/page-name/ while hiding the url lang parameter for default language. Also a minor unrelated question, cheked the html example: I do have to create one page per language right?

_Originally posted by @tomasts248 in https://github.com/Irrelon/jquery-lang-js/issues/131#issuecomment-761158646_

**Comment by Irrelon** [comment]
Closing as already responded in other thread and no follow up response provided.
