### ISSUE TITLE
Can not translate 2 regex in same block

### ISSUE THREAD

**Issue by roha69** [Irrelon/jquery-lang-js#30]
Hi,

I have this text :
![capture](https://cloud.githubusercontent.com/assets/6988664/3854095/fb5f502e-1ed1-11e4-9e93-ff0da22946ec.PNG)

(HTML CODE)
![capture3](https://cloud.githubusercontent.com/assets/6988664/3854131/76791e7a-1ed2-11e4-95a1-61499bfde6a2.png)

i have this translation in french :
![capture2](https://cloud.githubusercontent.com/assets/6988664/3854110/38144f38-1ed2-11e4-9057-c79b568370cc.PNG)

I have 2 regex, but only one work (Finish).
![capture4](https://cloud.githubusercontent.com/assets/6988664/3854159/d9266208-1ed2-11e4-8832-3770fe1d90ec.PNG)

and without ["Finish","Terminé"], it's working but Finish is not translate ...
![capture5](https://cloud.githubusercontent.com/assets/6988664/3854177/2568c21e-1ed3-11e4-8996-874d41ef2a6e.PNG)

Thanks

**Comment by dalekeys12** [comment]
This was my next question and I suppose your right speed would become an issue as your data gets larger.   Everything else works perfect. 

Thanks
Dale
