### ISSUE TITLE
HTML characters not working

### ISSUE THREAD

**Issue by getandyjones** [Irrelon/jquery-lang-js#38]
Hi,

I have used various special characters in my german translation - but they are being garbled by the HTML - for example:

können

Is being rendered as: k�nnen

My other languages are OK - any suggestions??

Thanks
Andy

**Comment by Irrelon** [comment]
Make sure your site page encoding is set to utf-8 and that your text editor is saving your language files (.json) using UTF-8 as well

**Comment by getandyjones** [comment]
Thanks - The page is already utf-8. I've also checked the text editor, and it's already saving as utf-8.
If I try and use html entities such as &pound; it doesn't translate it into the £ character either. Is there no way that these characters can work?

**Comment by Irrelon** [comment]
All UTF-8 characters work and the plugin was specifically designed to support them because foreign language glyphs are almost all in the UTF-8 space. I have personally tested many currency symbols and language glyphs for both English and non-English languages. We use the plugin in production on https://www.orbzu.com and there are no issues with symbols.

It is almost always an encoding issue when you see those question marks inside a diamond. What is the web address for your page where this is happening? I would bet good money it is not an issue with the plugin since it is being widely used by many people!

**Comment by getandyjones** [comment]
Thanks - it was the encoding of the json file - strange though, as i couldn't change it but when i created a new file and copied the text in it resolved the issue. I'm now having issues where some people are saying that on Internet Explorer they cannot change the language - have you come across this before?

**Comment by Irrelon** [comment]
No but it would be interesting to know what version of IE is causing trouble...

**Comment by getandyjones** [comment]
Yes I've asked that and they said '2011' lol...

Regards,

Andy

Visit our web site: http://www.tygamarketing.com
____________________________________________

Andy Jones
Creative Director
TYGA Marketing Limited
TYGA House, 13 Alban Park, Hatfield Road, St. Albans, Herts, AL4 0JJ
T: 01727 898 191  F: 01727 898 190
W: http://www.tygamarketing.com
____________________________________________

**Comment by Irrelon** [comment]
LOL oh dear...

**Comment by getandyjones** [comment]
HI There,

I have had a report that the plugin isn't working on IE9 on Windows 7.
I have tested in browserstack, and it's not changing when I click the flags
- see below:
http://buyonboard.easyjet.com

It seems to work in all other browsers (but typical that this is the
browser the client is using!!)

Any advise of what to try?

Thanks in advance!

Regards,

Andy

Visit our web site: http://www.tygamarketing.com
____________________________________________

Andy Jones
Creative Director
TYGA Marketing Limited
TYGA House, 13 Alban Park, Hatfield Road, St. Albans, Herts, AL4 0JJ
T: 01727 898 191  F: 01727 898 190
W: http://www.tygamarketing.com
____________________________________________

**Comment by Irrelon** [comment]
I will check this as a matter of priority. IE9 on Win7 has always worked in the past. Do you have access to the JavaScript console log? That might help narrow the issue down.

**Comment by Irrelon** [comment]
Found the issue (I believe). The console object doesn't exist in IE9 when the dev tools are shut so console logs will error. I will push a new version of the plugin without console.log() calls...

**Comment by getandyjones** [comment]
Great OK thanks!
Will you let me know when this is fixed?



Regards,

Andy

Visit our web site: http://www.tygamarketing.com
____________________________________________

Andy Jones
Creative Director
TYGA Marketing Limited
TYGA House, 13 Alban Park, Hatfield Road, St. Albans, Herts, AL4 0JJ
T: 01727 898 191  F: 01727 898 190
W: http://www.tygamarketing.com
____________________________________________

**Comment by Irrelon** [comment]
I've updated the code. Could you let me know if that solves it for you?

**Comment by getandyjones** [comment]
Great thanks - ill check first thing tomorrow.

Andy

Sent from my iPad

On 7 Jan 2015, at 19:35, Rob Evans <notifications@github.com> wrote:

I've updated the code. Could you let me know if that solves it for you?

—
Reply to this email directly or view it on GitHub
<https://github.com/Irrelon/jquery-lang-js/issues/38#issuecomment-69077980>.

**Comment by getandyjones** [comment]
Yep - that fixed the issue - nice one - thanks!

Regards,

Andy

Visit our web site: http://www.tygamarketing.com
____________________________________________

Andy Jones
Creative Director
TYGA Marketing Limited
TYGA House, 13 Alban Park, Hatfield Road, St. Albans, Herts, AL4 0JJ
T: 01727 898 191  F: 01727 898 190
W: http://www.tygamarketing.com
____________________________________________

**Comment by Irrelon** [comment]
Excellent. IE really is horrible. Glad they've fixed most of this in IE11 but took so long to get there. Glad the market share for IE overall is now below 10% worldwide :)

**Comment by getandyjones** [comment]
Here here! I still have to support ie6 on one site - only because that's
what the client uses!!! ha ha..!!

Regards,

Andy

Visit our web site: http://www.tygamarketing.com
____________________________________________

Andy Jones
Creative Director
TYGA Marketing Limited
TYGA House, 13 Alban Park, Hatfield Road, St. Albans, Herts, AL4 0JJ
T: 01727 898 191  F: 01727 898 190
W: http://www.tygamarketing.com
____________________________________________
