### ISSUE TITLE
Language Switch - Grid Support

### ISSUE THREAD

**Issue by dalekeys12** [Irrelon/jquery-lang-js#40]
Hi Guys.
 
I am currently working on an web application in classic ASP and just had a quick question about the use of grids.

Is it possible that this could be used to switch the grid text as well?  The grid I am using is VSFlexGrid8.
 
http://www.componentone.com/SuperProducts/VSFlexGridPro/
 
If this would not work can you recommend one that would?  I would like to use somthing like your tool as it would mean not changing the data source in the back end. 
 
Many thanks for any advance! 
Dale

**Comment by Irrelon** [comment]
Hi Dale,

I'm not familiar with the grid you are using but if it outputs HTML then it can be translated. If it is an ActiveX control then I suspect that it cannot be translated unless you are manually setting cell values using JavaScript and can run them through the js translator first (you can manually translate any text by calling .translate(text); ).

Is the control an ActiveX control? If so it will only work on Internet Explorer anyway and there are many alternatives that are cross browser that would probably work better for you.

Is there any reason why you wanted to use VSFlexGrid8? I've not played around with ActiveX for around 18 years though (since my early VB6 days) so I don't know the current state of play with that stuff.

**Comment by dalekeys12** [comment]
The app im trying to use this on is an old lagacy app that could be more hastle than its worth by replacing the grids.   And yeah its Active X which is a pain but the internet explorer issue is not really a problem.

I connect in ASP to a database and then populate the Grid as shown below.

<SCRIPT LANGUAGE=VBScript>
....
  RB1_MyTestGrid.AddItem vbTab & ("1" & vbTab & "Row Content 1")
  RB1_MyTestGrid.AddItem vbTab & ("2" & vbTab & "Row Content 2")
  RB1_MyTestGrid.AddItem vbTab & ("3" & vbTab & "Row Content 3")
  RB1_MyTestGrid.AddItem vbTab & ("4" & vbTab & "Row Content 4")
  RB1_MyTestGrid.AddItem vbTab & ("5" & vbTab & "Row Content 5")
</SCRIPT>

Does the switch work in vbscript or will I have to try and populate this using javascript?
If this is not possible have you used any other Grids that this could work for? 

Thanks again for the help getting no where with converting Grids!
 :)

**Comment by Irrelon** [comment]
Hmm... can you call JavaScript methods from VBScript? I've never used it! If so you should be able to translate without issue.

If not I would suggest grabbing almost any jQuery-based sortable table / grid and using that. You can output a standard HTML table from the ASP and then latch onto it with jQuery to make it sortable.

The main issue here is it's an ActiveX control so it's not web-native HTML stuff. The language plugin is designed to work with open web standards and is built entirely with JavaScript in mind.

**Comment by dalekeys12** [comment]
This is how I am populating the Grid in VB Script. 

SCRIPT LANGUAGE=VBScript
RB1_MyTestGrid.AddItem vbTab & ("2" & vbTab & "Test 123")
RB1_MyTestGrid.AddItem vbTab & ("3" & vbTab & "Test 123")
RB1_MyTestGrid.AddItem vbTab & ("4" & vbTab & "Test 123")
/Script

And I know in VBScript I can call a Javascipt function as shown below with a simple alert.

script type="text/javascript"
     function jsfunction()
     {
          alert("Hello")
     }
/script

SCRIPT LANGUAGE=VBScript
      Sub window_onLoad
          jsfunction() 
      End Sub
/SCRIPT


Just not sure how I could then wrap the convert around the : 
RB1_MyTestGrid.AddItem vbTab & ("2" & vbTab & "Test 123")

Possibly would be better trying to move away from this old Grid as you suggest, im sure there are much better things out there! lol  

Thanks

**Comment by Irrelon** [comment]
Based on that it should be pretty easy to wrap the translate method around each bit of text...

But I don't know how you get a value back from a call to JavaScript in VBScript.

What you need to be able to do is something like:

```
SCRIPT LANGUAGE=VBScript
Sub window_onLoad
myTranslatedText = lang.translate("Test 123"); 

RB1_MyTestGrid.AddItem vbTab & ("2" & vbTab & myTranslatedText)
End Sub
/SCRIPT
```

Would something like that work in VBScript?

**Comment by dalekeys12** [comment]
Got it sorted Rob!  Wouldn't let me call the lang.translate directly in VBScript so I created a JavaScript function to perform the translation then called this JavaScript function in my VBScript to populate the grid.  Just need to perform a refresh on the page when you change language and it works perfect.

Script Type="text/javascript"
		function jsTranslate(Sourcetext)
		{
			return lang.translate(Sourcetext);
		}
/script


SCRIPT LANGUAGE=VBScript
		RB1_Process_List.AddItem vbTab & jsTranslate("1" & vbTab & "This ")
		RB1_Process_List.AddItem vbTab & jsTranslate("2" & vbTab & "Machine")
/SCRIPT


I have another question about the Regex translations but I'll create another issue.

Thanks!
Dale

**Comment by dalekeys12** [comment]
I had an issue with multiple columns when I use this method.

When I use my translate function as shown below:

  RB1_Process_List.AddItem vbTab & jsTranslate("2" & vbTab & "Translation one" & vbTab & "Another Translation" & vbTab & "And Another Translation")

It passes the following to the function:
"2\tTranslation one\tAnother Translation\tAnd Another Translation"

To which the output will be:
"2\t任何时候 \t Another Translation \t And Another Translation"

This is because it hits the 1st translation then returns the full string.  I used a basic function to translate each section between the /t.

function TranslateDatabase(Sourcetext)
{
		var RowArray = Sourcetext.split("\t") //  \t split for each column
		var translation = ""
		console.log("New Column to Translate:  " + Sourcetext);
				
		for (var i = 0; i < RowArray.length; i++)
		 {
			translation =  translation + lang.translate(RowArray[i]) + "\t"
		 }
	
		console.log("Translation:  " +translation);
		return translation;
}


This could be used to translate a sentence by replacing the \t with a space.  Not sure if it would make much sense tho.

Thanks, 
Dale
