### ISSUE TITLE
How to change both the <a> href attribute and the link's label?

### ISSUE THREAD

**Issue by goyosoyo** [Irrelon/jquery-lang-js#42]
I need to switch the url as well as the link's label.  What's the best way to do this?

I tried a number of ways but wasn't successful, including:

<a href="english/version/url" lang="en" target="new">English Link Label</a>

In the non-dynamic.js file I have 
Lang.prototype.pack.es = {
"English Link Label":"Translated Link Label",
"english/version/url":"translated/version/url"
}

The link label translates but the url does not.

Thanks,
Greg

**Comment by Irrelon** [comment]
Does your link element include a *lang* attribute?

**Comment by goyosoyo** [comment]
![code snippet](https://cloud.githubusercontent.com/assets/895219/6274813/08e536b8-b82f-11e4-8d70-66d1f9aa5cc6.gif)

**Comment by Irrelon** [comment]
Could you provide a page with your code on it? I will need to inspect the JS console and step through the code to see why this isn't working for you.

**Comment by goyosoyo** [comment]
http://psdev.etr.org/wccusdDEV/index.cfm?fuseaction=public.complaint

**Comment by goyosoyo** [comment]
Sorry, should have included in the above post to please look at the link 'A copy of the District's AR 5145.3 is available free of charge.'  This is where the issue I'm having is located.

**Comment by Irrelon** [comment]
Your version of the plugin is out of date so it will not translate href attributes. Please update your jquery-lang.js file :)

**Comment by goyosoyo** [comment]
Yes, successful now.  Thank you. 
Regards,
Greg
