### ISSUE TITLE
escaping double qoutes

### ISSUE THREAD

**Issue by chrisjbrown** [Irrelon/jquery-lang-js#44]
How can I include double quotes?

ex: 
{
 "Please click "next" to proceed": "bla bla "next" bla"
}

normal json escaping throws error on loading language
ex:
{
 "Please click /"next/" to proceed": "bla bla /"next/" bla"
}

**Comment by Irrelon** [comment]
Aren't those escapes the wrong ones? Can you try backslashes?

**Comment by chrisjbrown** [comment]
Damn, your right. My bad.

**Comment by Irrelon** [comment]
;)
