### ISSUE TITLE
Question about jqueryui dialog buttons

### ISSUE THREAD

**Issue by actarusvb** [Irrelon/jquery-lang-js#45]
Hi,
i'm facing to translate the dialog buttons text, i can't set the lang attribute to the <span></span> tag used to include the button text.

Any suggestion ?

Thanks in advance

**Comment by roha69** [comment]
You have the actual language with javascript. Just use the fonction for translate dynamically. Personnaly, i throw a event when language change. So I have old language, new language and can translate all "javascript word" in real time.
