### ISSUE TITLE
Translating after loading new dynamic content

### ISSUE THREAD

**Issue by nathan14** [Irrelon/jquery-lang-js#47]
Hey guys,

Fist of all thank you for this - really easy to use and simple.
In my website, some content is being loaded dynamically with ajax and includes new html...
for example, i'm loading this - <span lang="en">Name</span>
now, when i'm trying to use the translation, it will only translate non-dynamic content of the page.
any ideas?

Thanks!

**Comment by roha69** [comment]
Try to load lang after the complete Ajax setup

**Comment by Irrelon** [comment]
Your dynamic content MUST:

a) Already include a lang attribute on any elements that you want translating
b) Be inserted onto the page via jQuery

Can you check if both these conditions are true?

**Comment by nathan14** [comment]
Thanks guys, made sure both conditions are true and now it's fine.

**Comment by Irrelon** [comment]
Cool :)
