### ISSUE TITLE
translate added dom elements

### ISSUE THREAD

**Issue by reno1979** [Irrelon/jquery-lang-js#49]
Perhaps this is more a request than an issue. 

I would like to be able to translate the entire page, even the added DOM components,

Most of the time it's very hard to add the lang attribute before the HTML is inserted in the DOM, I could modify all the used plugins, but that is not a real solution. 

For know I gave all elements that need translation a translatable class, the called function to activate the change() also translates every found componten with the translatable classname.

**Comment by Irrelon** [comment]
Hey ya, the capability to translate all HTML on the page or being added would be a massive performance killer (I think). You'd have to iterate through the entire dom and search every string for every potential match.

Not sure what you're asking is possible with any plugin. Would be open to discussing further though :) I like to keep an open mind.

**Comment by kennyk-peplink** [comment]
I've tested with jquery-lang to translate all DOM elements (without lang tag), the performance on existing jquery-lang is unrealistic.

It is do-able, however, by fixing-up some repeat entrance, I'm running exactly what you suggested in an existing in-house project that does not dare to add any further lang tag in each DOM elements.

It's now like a plug and play, in reasonable performance.
jquery-lang has such potential.

**Comment by Irrelon** [comment]
@kennyk-peplink Would there be any way to add this as an option into the existing code base and then merge your changes, so that existing users don't have breaking changes but the option could fulfill the requirement as laid out above?

**Comment by kennyk-peplink** [comment]
My changes is definitely a breaking changes (at this moment) just to fit our need.

I may share my patch to you if that inspire the possibility to fit into your existing source to work gracefully.

**Comment by Irrelon** [comment]
Cool. Is it in a fork on github? If so that would be the easiest way to
share as I can directly compare the code.

**Comment by kennyk-peplink** [comment]
I've put the patch under "my_hack", for your reference.

**Comment by reno1979** [comment]
Have you seen the jquery observe plugin? It uses the DOM mutation observer and is very fast. 

I was planning to use this to monitor the body (or any other)  tag for added / changes elements that contain the language tag. (very fast and reliable)  

The problem however is that I have not yet figured out how to let this plugin translate that component. (ok translated text works, but that does not look at the value of the lang attributes and so does not switch.

**Comment by Irrelon** [comment]
@kennyk-peplink Thanks :)

**Comment by Irrelon** [comment]
@reno1979 I have, but mutation observers are not fully supported by browsers yet AFAIK. I'm trying to keep support for some users who are dragging their heels on updating. (IE sucks huh?)

**Comment by reno1979** [comment]
@Irrelon 

Ok I understand, but how do I trigger a translate action on an element manualy??

I don't mean this : 
$(this).text(window.lang.translate($(this).text()));

But the same event that is triggered on windows.lang.change

**Comment by reno1979** [comment]
But how can I start a translate action manually on a dom component (an
action that looks at the value of the lang attribute.
Op 24 jun. 2015 12:25 schreef "Rob Evans" <notifications@github.com>:
