### ISSUE TITLE
Translate long text

### ISSUE THREAD

**Issue by ledzgio** [Irrelon/jquery-lang-js#50]
How can I translate long text? What if I have a very long text I want to translate using the plugin?

thanks

**Comment by Marox44** [comment]
Yep, I'm wondering about it too :) Let's say I have a paragraph of text (long one), what is a proper way to translate it?

Thanks in advance, and a solid appreciation from me - that's a great and rly usefull plugin indeed :)

**Comment by dalekeys12** [comment]
Just do a paragraph at a time?  or sentence.  Converting single words will never make any sense.

**Comment by dalekeys12** [comment]
You could use a function below to pass in a bulk of text and loop through and translate every word or every sentence depending on the split function.

function TranslateBulkText(Sourcetext)
{
        var RowArray = Sourcetext.split(".") //  . split for each Sentence
        var translation = ""

        for (var i = 0; i < RowArray.length; i++)
         {
            translation =  translation + lang.translate(RowArray[i]) + "\t"
         }
        return translation;
}

You could change Sourcetext.split(".")  to Sourcetext.split(" ") to do single words however I think it would be useless.

Thanks

**Comment by kevkha** [comment]
I translate a paragraph at a time and it seems to work fine for me.
```html
<p lang="en">My long text goes here.</p>
<p lang="en">My other long text goes here.</p>
```
As long as the JSON file has the exact input text including any punctuation.
```JSON
	"token": {
		"My long text goes here.":"Your translation goes here.",
		"My other long text goes here.":"Your translation goes here."
	},
```
What I wish to have is an ability make some texts in a paragraph bold (strong) part of a plugin.

**Comment by thejae** [comment]
Am building a corporate website, they have huge amount of copy and in several languages. It wouldn't make sense if I duplicate a 300 word long lorem ipsum paragraphs again and again over multiple language.

Can we get a ID tag? For e.g

`<p lang="en" data-lang-id="21">Lorem ipsum.... .... .. </p>`

And in the JSON
````
/* Fr  */
"id": {
     21: "Le lorem ipsum... .."
}

/* De */
"id": {
    21: "Die lorem ipsum... .."
}

/* It */
"id": {
    21: "Il lorem ipsum... .."
}

**Comment by kevkha** [comment]
@thejae Good idea! +1

**Comment by madrabaz** [comment]
+1

**Comment by Irrelon** [comment]
Keep in mind guys that l18n is more about token replacement on web apps than it is about translating entire pages of text. But if you really want to do it, translating by paragraph is the way forward in my opinion (as the library creator).
