### ISSUE TITLE
add v2.6.0~v2.8.0 tags

### ISSUE THREAD

**Issue by Amomo** [Irrelon/jquery-lang-js#53]
Hi

I found that jquery-lang-js is v2.8.0 now, but the latest tag is still 2.5.0.
Would you consider adding v2.6.0~v2.8.0 tags?

Thank you!

**Comment by hozza** [comment]
I agree, please add the new tags @Irrelon ! :)

**Comment by Irrelon** [comment]
I'm so used to having an automated build system I forgot there isn't one for this project that creates tags and versions etc automatically. I'll get around to this soon!!

**Comment by Irrelon** [comment]
Done. 2.6.0 doesn't exist but 2.7.0 and 2.8.0 do and are now on github.
