### ISSUE TITLE
Language doesen't change

### ISSUE THREAD

**Issue by fafualex** [Irrelon/jquery-lang-js#56]
When I click on "switch to language" it does nothing and on chrome console I have this issue message showing up: "Uncaught TypeError: Cannot read property 'change' of undefined".. 
It means that "window.lang.change" doesn't work as it does in your original project.. I can't figure out what the problem is.. Thanks in advance.

**Comment by ridom** [comment]
Hi,

I am experiencing the same issue, have you been able to fix it?

Thanks!

**Comment by HOllarves** [comment]
Me too! Any info on this?

**Comment by ridom** [comment]
Sorry I haven't found a solution.
Maybe a conflict between scripts. Let me know if you get something!

**Comment by ridom** [comment]
@fafualex ?

**Comment by fafualex** [comment]
Hi, yes I managed to get everything working except for language to stay changed when refreshing the page or going in an other page of the website. But it was long time ago and I don't remember what the problem was..

**Comment by ridom** [comment]
Hi
Ok, thanks for the reply. So it's about the cookie side but not the proper language plugin.
Thanks anyway
