### ISSUE TITLE
Custom cookie token name

### ISSUE THREAD

**Issue by kevkha** [Irrelon/jquery-lang-js#60]
To prevent a conflict with the predefined token name <code>langCookie</code> I suggest the plugin to accept a custom token name (don't hardcode the <code>langCookie</code> but let the dev to name it outside). This would be a good enhancement. Thoughts?

**Comment by Irrelon** [comment]
Definitely makes a lot of sense and I fully agree with that idea!

I'm not in a position to make any updates to this library at the moment as I have my hands full with ForerunnerDB right now but if someone wanted to take a stab at it and do a pull request ... :)

**Comment by kevkha** [comment]
I think I got it working here https://github.com/kevkha/jquery-lang-js

**Comment by Irrelon** [comment]
Now part of 3.0.0
