### ISSUE TITLE
Demo do it work?

### ISSUE THREAD

**Issue by hszili76** [Irrelon/jquery-lang-js#62]
Hi!

I downloaded the zip file, and if open the index.html file, when not working.
Is not change the language.
What I'm doing wrong?
I tried to step by step too,  a my site and it will not working.
I don't know, what i'm doing wrong
Thank You
Regards

**Comment by Irrelon** [comment]
The demo must be run from a web server. Check your javascript console in your browser for any errors.

**Comment by hszili76** [comment]
I tried 3 browsers (safari,chrome,firefox). Its not working.
I don't know, what i'm doing wrong
webserver: szilipage.com

Thanks

**Comment by Irrelon** [comment]
Like I said you need to check your javascript console. It provides all the error information you need :)

**Comment by hszili76** [comment]
Sorry,  I don't understand. The all browsers enabled the javascript. where to find the javascript console?

**Comment by visualcohol** [comment]
There is an issue in Demo, thets why its not working
In index.html on line:7 - "<script src="js/js-cookie.js" should be "<script src="js/js.cookie.js"

**Comment by hszili76** [comment]
Thanks, once more :-)

**Comment by kevkha** [comment]
Sorry guys. It was my mistake. Glad it's fixed.
