### ISSUE TITLE
Issue with dynamic loading language

### ISSUE THREAD

**Issue by Bob-programmer** [Irrelon/jquery-lang-js#65]
Hi,

I am testing loading the languages dynamically and its not working. should be a small issue on my end. If you can let me know that would be great.

here is whats happening. If i am on the home page(index.html) and then change the language to english from italian it works. if i move to second page (index2.html) it reverts back to italian which is the default language. 

Also the other issue i noticed was some times the when switching between languages it  fails with a error message on the cosole about "language pack not Found"

see the screenshot below.

![firstpage](https://cloud.githubusercontent.com/assets/16078944/11467146/70291958-9703-11e5-81ec-a7d4f8bfdd10.png)
![page2](https://cloud.githubusercontent.com/assets/16078944/11467147/702c60ae-9703-11e5-8e90-f0a6c7e3c500.png)

I am also attaching the project files for your reference.

Strange thing the same code works without any issues when loading the language non-dynamically i.e using the nondyanmic.js 

**en.json**

```
{
    "token": {
        "L'azienda": "The winery",
        "I vini": "Wines",
        "Questo è l'indice principale Pagina": "This is the Main Index Page",
        "Questo è il Index2 Pagina": "This is the Index2 Page",
        "Pagina 1": "Page 1",
        "Pagina 2": "Page 2"
    }
}
```

**index.html**

```
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>jQuery Lang JS Module Test Page</title>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js" type="text/javascript"></script>
    <script src="js/js.cookie.js" charset="utf-8" type="text/javascript"></script>
    <script src="js/jquery-lang.js" charset="utf-8" type="text/javascript"></script>
    <script type="text/javascript">
        var lang = new Lang('it');
    </script>
    <style>
        body {
            font-family: Verdana, Geneva, sans-serif;
            font-size: 12px;
        }

        #langChanger {
            margin-bottom: 10px;
        }

        .sectionTitle {
            font-weight: bold;
            font-size: 14px;
            margin-bottom: 10px;
        }
    </style>
</head>

<body>
<div id="langChanger"><a href="#" onclick="window.lang.change('it'); return false;">Switch to IT</a> | <a href="#" onclick="window.lang.dynamic('en','js/langpack/en.json');window.lang.change('en'); return false;">Switch
    to EN</a></div>
<div id="testHtml">
    <h1 lang="it">L'azienda</h1>
    <h2 lang="it">I vini</h2>
    <div lang="it">Questo è l'indice principale Pagina</div>
    <a href="index2.html" lang="it">Pagina 2</a>
</div>
</body>
</html>

```

**index2.html**

```
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>jQuery Lang JS Module Test Page</title>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js" type="text/javascript"></script>
    <script src="js/js.cookie.js" charset="utf-8" type="text/javascript"></script>
    <script src="js/jquery-lang.js" charset="utf-8" type="text/javascript"></script>
    <script type="text/javascript">
        var lang = new Lang('it');
    </script>
    <style>
        body {
            font-family: Verdana, Geneva, sans-serif;
            font-size: 12px;
        }

        #langChanger {
            margin-bottom: 10px;
        }

        .sectionTitle {
            font-weight: bold;
            font-size: 14px;
            margin-bottom: 10px;
        }
    </style>
</head>

<body>
<div id="langChanger"><a href="#" onclick="window.lang.change('it'); return false;">Switch to IT</a> | <a href="#" onclick="window.lang.dynamic('en','js/langpack/en.json');window.lang.change('en'); return false;">Switch
    to EN</a></div>
<div id="testHtml">
    <h1 lang="it">L'azienda</h1>
    <h2 lang="it">I vini</h2>
    <div lang="it">Questo è il Index2 Pagina</div>
    <a href="index.html" lang="it">Pagina 1</a>
</div>
</body>
</html>
```

Any help will be greatly appreciated. Please let me know how i can fix this.

Thanks in Advance,
Bob :)

**Comment by Irrelon** [comment]
Hi Bob,

First can I say *thank you* for such a thorough and well written issue / question... it's rare to see that much detail and it's very helpful! :)

I think the main issue *might* be that you declare the dynamic pack using the onclick... could you register it in your <head>:

So move:

    window.lang.dynamic('en', 'js/langpack/en.json');

To your head so it looks something like this:

    <script src="js/jquery-lang.js" charset="utf-8" type="text/javascript"></script>
    <script type="text/javascript">
        window.lang.dynamic('en', 'js/langpack/en.json');
    </script>

Give that a go for fixing the language loading issue. Also if you can throw this up onto a server we can access that would be cool so if any further issues arise we can try to debug it too.

**Comment by Bob-programmer** [comment]
Rob,

Thanks for your reply. I moved the code and its still the same.

I will try to explain the design that i am trying to implement.

For ex in my site the default language is Italian. There will be a button for the user that says Load English. When users click on the button, i want to load the english language (en.json) and convert the text to english, else i want to leave the site in Italian.

As told earlier, i moved the code to java script like this and its still not working properly, meaning if i change the language on page 1 it changes and when i move to page 2, its reverting back to Italain.

index.html after moving the code to the 
```
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>jQuery Lang JS Module Test Page</title>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js" type="text/javascript"></script>
    <script src="js/js.cookie.js" charset="utf-8" type="text/javascript"></script>
    <script src="js/jquery-lang.js" charset="utf-8" type="text/javascript"></script>
    <script type="text/javascript">
        var lang = new Lang('it');

    </script>
    <style>
        body {
            font-family: Verdana, Geneva, sans-serif;
            font-size: 12px;
        }

        #langChanger {
            margin-bottom: 10px;
        }

        .sectionTitle {
            font-weight: bold;
            font-size: 14px;
            margin-bottom: 10px;
        }
    </style>
    <script type="text/javascript">
    function loadEnglishlanguage()
        {
            window.lang.dynamic('en','js/langpack/en.json');
            window.lang.change('en');
            return false;
        }
    </script>

</head>

<body>
<div id="langChanger"><a href="#" onclick="window.lang.change('it'); return false;">Switch to IT</a> </div>
         <button onclick="loadEnglishlanguage()">Load English</button>
<div id="testHtml">
    <h1 lang="it">L'azienda</h1>
    <h2 lang="it">I vini</h2>
    <div lang="it">Questo è l'indice principale Pagina</div>
    <a href="index2.html" lang="it">Pagina 2</a>
</div>
</body>
</html>

```

The same code works fine, if i use the nonDyanamic.js and load it then the language persists across pages and works fine.

For your reference, i will try push both the versions (i.e dynamic and non-dynamic) online that way you can test it.

Thanks,
Bob

**Comment by Bob-programmer** [comment]
Rob,

I pushed the code online and there are two versions the dynamic one thats not working and the nonDynamic one thats working.

1. dynamic language code which is not working.
   * http://htmsite-bobtheprogrammer.rhcloud.com/index.html
2. nonDynamic language code which is working.
   * http://htmsite-bobtheprogrammer.rhcloud.com/nonDynamic/index.html

Please test those URL's and let me know as to what changes i need to make to make it work.

Thanks,
Suman

**Comment by Irrelon** [comment]
Hi thanks for uploading test pages.

I have pushed a new version of the library (version 3.0.0) that includes a new readme that explains how to use dynamic packs better. Could you install version 3, check the readme and let me know if that is now working for you?

Cheers!

Rob
