### ISSUE TITLE
go to languge from URL?

### ISSUE THREAD

**Issue by getandyjones** [Irrelon/jquery-lang-js#66]
Hi,

Is it possible for the user to type something like example.com?lang=fr in their browser address bar and load the french translation automatically, rather than having to click the flags each time?

**Comment by Irrelon** [comment]
Of course. That is entirely a JavaScript question though, it's not really related to this library. You can get the query parameters of the current URL in JavaScript and then ask the library to switch languages appropriately.

Check google for details on how to read query parameters from a url, that will get you started :)
