### ISSUE TITLE
How to Translate Header Tags like H1 H2 H3.

### ISSUE THREAD

**Issue by kunalthecoder** [Irrelon/jquery-lang-js#67]
Hi,

Below is my HTML which is not getting translated.
<.h1 lang="th">
        Floor Plans
    <.h1>'

Please help me with this.

Thanks,
Kunal

**Comment by kevkha** [comment]
You have a period before <code>h1</code> tags?

**Comment by kunalthecoder** [comment]
If I will remove that dot then it will render that as HTML in Comments.

Anyways the issue is solved.
