### ISSUE TITLE
More details of regex in th.json

### ISSUE THREAD

**Issue by supun151515** [Irrelon/jquery-lang-js#69]
There is no good tutorial about regex in th.json. Kindly explain about it.

jquery-lang-js-master/index.html example page at the bottom, dynamic text<b> 'Something'</b> is not getting translated.

Thank You,
Supun

**Comment by Irrelon** [comment]
Regular expressions are defined (as shown at https://github.com/Irrelon/jquery-lang-js#define-a-language-pack) by providing three arguments in an array.

The arguments are:

    [<your regular expression>, <your regexp options>, <your replacement text>]

This is equivalent to the JavaScript RegExp() object which uses the first two arguments e.g.

    new RegExp(<your regular expression>, <your regexp options>);

You can read about JavaScript's RegExp system from MDN.
