### ISSUE TITLE
Translation value contains HTML tags

### ISSUE THREAD

**Issue by Dossea** [Irrelon/jquery-lang-js#77]
I'd like to enrich my translation using HTML tags like:
"This is some translated <strong>text</strong>"

so that it results in:
This is some translated **text**

Is there a way to do this?

Thank you advance!

**Comment by Et3rnal** [comment]
Hi mate, did find anyway to make this work? I have the same situation now.

**Comment by Kimyuhwan** [comment]
Hi, I run into the problem also. Is there any way to do that?

**Comment by Dossea** [comment]
I'm glad to see that I'm not the only one with this question.
Have you found a solution yet? I just overwrote the Lang.prototype._setTextNodes function to get my things working.
I can send you guys my version if you don't know how to override it.

**Comment by ojedawinder** [comment]
Hi guys, how you managed to solve the problem , I need to translate text with internal html tags.

**Comment by cbje** [comment]
@Dossea Can you please share what code you used to overwrite the function?

**Comment by cbje** [comment]
@Dossea 
I only have basic JS skills but I started a fork that can read HTML entities from the JSON [here](https://github.com/cbje/jquery-lang-js/blob/master/js/jquery-lang.js).
Only limitation is that it does not correctly overwrite the original language if there are innerHTML elements, but I am working on it.

**Comment by cbje** [comment]
@ojedawinder
I started a fork that can read HTML entities from the JSON [here](https://github.com/cbje/jquery-lang-js/blob/master/js/jquery-lang.js).
Only limitation is that it does not correctly overwrite the original language if there are innerHTML elements, but I am working on it.
