### ISSUE TITLE
How to Translate Text which are Rendered using Pseudo Selectors in CSS? like ::after and ::before

### ISSUE THREAD

**Issue by kunalthecoder** [Irrelon/jquery-lang-js#81]
Hi,

We have pseudo selectors in CSS and we can specify contents over there.

How to Translate texts specified using Pseudo selectors?

**Comment by Irrelon** [comment]
I don't think that is possible since the text isn't actually a text node in the DOM, it is a CSS selector.

**Comment by kunalthecoder** [comment]
Hi Thanks for your reply.

I have solved above issue using below code.

// Before Pseudo Selector
`var style = '';")
$(document.querySelectorAll('*')).each(function(index, item){
var pE = window.getComputedStyle(item, ':before').getPropertyValue('content');
if (pE.charAt(0) === '""' && pE.charAt(pE.length -1) === '""')
{
pE = $.trim(pE.substr(1,pE.length -2));
} 
var myText  = lang.translate(pE);
if(pE)
{ 
  if(pE != myText) 
  { 
     var cssClassName = 'mylangBefore-' + index;  style += '.' + cssClassName + ':before { content: ""'+ myText +'"" !important; }';
     $(item).addClass(cssClassName);
   }")
}
});

// After Pseudo Selector
$(document.querySelectorAll('*')).each(function(index, item){
var pE = window.getComputedStyle(item, ':after').getPropertyValue('content');
if (pE.charAt(0) === '""' && pE.charAt(pE.length -1) === '""')
{
pE = $.trim(pE.substr(1,pE.length -2));
} 
var myText  = lang.translate(pE);
if(pE)
{ 
  if(pE != myText) 
  { 
     var cssClassName = 'mylangAfter-' + index;  style += '.' + cssClassName + ':after { content: ""'+ myText +'"" !important; }';
     $(item).addClass(cssClassName);
   }
}
});`
