### ISSUE TITLE
Unable to run it in local

### ISSUE THREAD

**Issue by david-06studio** [Irrelon/jquery-lang-js#82]
Hi, works great online, great piece of script you got there !

But for a project, i need to run html pages offline (from an usbkey per example with no internet). In Firefox (PC) it work great but not with Chrome/IE. here the error from the console :

`XMLHttpRequest cannot load file:///C:/path/to/file/jquery-lang-js-master/js/langpack/th.json. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.`

i notice a problem with reading json file when protocol schemes. is there a way to run it (since it run already in firefox) ?

Regards and Cheers !
David

**Comment by Irrelon** [comment]
This is caused by Chrome's security settings. To get around this you have to include your lang packs using script tags and don't use dynamic loading. Take a look at loading the packs upfront here:

https://github.com/Irrelon/jquery-lang-js#including-language-packs-up-front-optional
