### ISSUE TITLE
Unable to translate text with html tags

### ISSUE THREAD

**Issue by Et3rnal** [Irrelon/jquery-lang-js#84]
Hi,

Thanks for the great plugin, I have a small problem when the plugin dont translate text that has any html tags on and iqnore them unless I remove the tags.

ex:

<p lang="en" data-lang-token="abouttxt">
This < b >APP< / b > can do a lot of things. 
</p>

now this will not be translated unless I remove the < b >< / b > tags?

Am I doing anything wrong?

**Comment by missaq** [comment]
Same problem with <br> tag. Did you find a solution?

**Comment by Et3rnal** [comment]
Nop, i just end up using the data-lang-token in each tag and removed all my formatting tags :|

**Comment by HansZwetslootAktionAktivAnarkist** [comment]
I write in English but my native language is Swedish. Would help work if Change to Swedish?

**Comment by cbje** [comment]
@Et3rnal @missaq @HansZwetslootAktionAktivAnarkist 
I only have basic JS skills but I started a fork that can read HTML entities from the JSON [here](https://github.com/cbje/jquery-lang-js/blob/master/js/jquery-lang.js).
Only limitation is that it does not correctly overwrite the original language if there are innerHTML elements, but I am working on it.

**Comment by Irrelon** [comment]
Hi I'm the original developer of the plugin. The plugin was designed for use in web applications / hybrid mobile applications that need to add l18n text translations to buttons, controls, titles, dialog boxes etc. While it can translate very large or long text sections, it was not intended to translate HTML, only pure text.

In cases where you have a whole page and you are not writing a web application, you are better off providing multiple versions of the page for each language and making your own switching links.

**Comment by HansZwetslootAktionAktivAnarkist** [comment]
I long for something to happend at my aerolab site. I dont able to manege myself
