### ISSUE TITLE
Set Class in CSS

### ISSUE THREAD

**Issue by missaq** [Irrelon/jquery-lang-js#85]
Hi Guys,
First of all, this is not a bug. Just a question.
For Example i have two a tags. One German one English. 
If the language English is the current i want set a class **active**.

`<a href='#' class='myBtn active'>English</a> | <a href='#' class='myBtn'>German</a>`

Any Idea?

**Comment by Irrelon** [comment]
I think you should be able to hook the change event from the plugin to set the css class via jQuery when the language switches.
