### ISSUE TITLE
Uncaught Error loading language pack js/langpack/en.json

### ISSUE THREAD

**Issue by gigallo** [Irrelon/jquery-lang-js#86]
I followed the guide to setup the library but I've got an error when firing 'window.lang.change('en');' event.
The error is:
Uncaught Error loading language pack js/langpack/en.json in jquery-lang.js:181
I don't understand where the problem is.

Any help?
Thanks

**Comment by ridom** [comment]
Hello Gigallo,

Have you been able to fix this issue?

Thanks for your help
Rom

**Comment by gigallo** [comment]
Yes thanks, it was a wrong / in the console error log

Regards

Gian Marco Gallo (da iPhone)

**Comment by millionart** [comment]
I have the same problem, maybe its a bug for IE
@Irrelon
