### ISSUE TITLE
Dynamic is undefined

### ISSUE THREAD

**Issue by ridom** [Irrelon/jquery-lang-js#87]
Hello,

I am experiencing an issue and I can't figure out where it comes from.

First lang switching :
_Uncaught TypeError: Cannot read property 'dynamic' of undefined_

Next :
_Uncaught TypeError: Cannot read property 'change' of undefined_

The website as few other scripts loaded before js.cookie.js and jquery-lang.js so maybe it could be the point.
I have test on website from scratch to make sure my files are ok and the process to integrate it is right and it works fine.

It's probably a noob issue impossible for me to solve it.
If someone could help me, I would really appreciate!
Thank you

**Comment by Irrelon** [comment]
In order to get help you usually have to show some code or point to the site you are seeing the issue with. From the information you have provided I don't think anyone can help at present.
