### ISSUE TITLE
(index):74 Uncaught TypeError: Cannot read property 'change' of undefined

### ISSUE THREAD

**Issue by HOllarves** [Irrelon/jquery-lang-js#88]
Hi, 

I'm having some issues trying to make the plugin work.

I'm currently using jquery 1.11.1

Loading both jquery-lang and the nondynamic lang pack through ruby //==require

my main.js looks like this

    `	//$(document).ready(function(){...
	var lang = new Lang();

	//lang.dynamic('en', 'assets/javascript/lang-pack/en-lang.json');

	lang.init({
		defaultLang: 'es'
	});

	Lang.prototype.attrList.push('h1');

	console.log(window);`

and my application.js 

`//= require 'theme/jquery-1.11.1'
//= require 'theme/jquery-lang'
//= require 'theme/js.cookie'
//= require 'theme/modernizr'
//= require 'theme/bootstrap.min'
//= require 'theme/owl.carousel.min'
//= require 'theme/jquery.fitvids'
//= require 'theme/smoothScroll'
//= require 'theme/nivo-lightbox.min'
//= require 'theme/jquery.scrollTo'
//= require 'theme/jquery.nav'
//= require 'theme/wow.min'
//= require 'theme/jquery.fs.wallpaper'
//= require 'lang-pack/en-direct-lang.js'
//= require 'theme/main'`

Both seem to be loading fine (network tab in chrome dev tools) but I get the following error when attempting to change language:

Cannot read property 'change' of undefined

Here's my navigation.html.erb:

`<nav class="navbar navbar-default navbar-fixed-top menu-navegacion" role="navigation" id="navigation-bar">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span>Menu</span>
      </button>

      <a class="navbar-brand" href="#intro">
        <img src="<%=image_path("logotipo.svg") %>" alt="Logo Social Doors" class="logo">
      </a>

    </div>

    <div class="lang pull-right">
      <li><a href="#lang-en" onclick="window.lang.change('en');" class="white-text">English</a></li>
      <li><a href="#lang-en" onclick="window.lang.change('es');" class="white-text">Español</a></li>
    </div>

    <div class="bar-anunciante-in-bar pull-right">
      <a href="/anunciantes/#beneficios" class="btn btn-custom btn-anunciante-in-bar">
        ¿Quer&eacute;s ser anunciante?
      </a>

    </div>

    <div class="navbar-collapse collapse  pull-right">
      <ul class="nav navbar-nav">
        
        <li class="current"><a href="#intro" class="white-text">Inicio</a></li>
        <li><a href="#detalles" class="white-text">Social Doors</a></li>
        <li><a href="#caracteristicas" class="white-text">Caracter&iacute;sticas</a></li>
        <li><a href="#categorias" class="white-text">Categor&iacute;as</a></li>
        <li><a href="#contacto" class="white-text">Contactanos</a></li>
        
      </ul>
    </div>
  </div>
</nav>
`

My intro.html:
    ` <h1 class="bajada" data-lang-token="mejores-salidas">Las mejores salidas, un solo lugar, siempre algo nuevo</h1>`

and en-lang.js:

    `Lang.prototype.pack.en = {
        "token": {
            "mejores-salidas":"The best go outs, in one place. Always something new"
        },
        "regex": [

        ]
    };
`

the website is in spanish so that's the default language, I just want it to change to english when the user click 'English' in the nav bar.

**Comment by HOllarves** [comment]
By putting it inside my <body> I managed to make the error disappear however, language is still not changing

**Comment by Irrelon** [comment]
Seems like a different way to bootstrap the library than the instructions in the readme. The lang.init() call needs to be made after the DOM has loaded. I suspect your main.js file is isolating the JS scope (which caused your first error of not finding window.lang) and then it is executing lang.init() before the DOM is available which would then cause future change requests to find no nodes to translate... this is just speculation because I have no experience with ruby require... never even heard of it until your post! I would imagine that if you include the main.js in a script tag at the end of your body tag you should get back up and running though.

**Comment by Irrelon** [comment]
Closed as no response.
