### ISSUE TITLE
How can I get Pre-built language packs?

### ISSUE THREAD

**Issue by anshabhi** [Irrelon/jquery-lang-js#89]
Is there some source from where I can get pre-built language packs for famous languages like French, German, Russian, Mandrin and Hindi?

**Comment by Irrelon** [comment]
Hi there, language packs cannot be pre-built since every web site has different phrases / tokens to translate.

**Comment by anshabhi** [comment]
Hi!

Sorry for the late reply. Thanks for your help!

**Comment by Irrelon** [comment]
@anshabhi That tool literally does not work. Just tested it against a Thai to English translation from the Thail language pack that the example I put together for this plugin uses.
