### ISSUE TITLE
Span data-hover how to translate?

### ISSUE THREAD

**Issue by raysefo** [Irrelon/jquery-lang-js#91]
Hi,

How can I translate this one?

`<span data-hover="Akıllı Park" lang="tr">Akıllı Park</span>`

Akıllı Park: Smart Parking

**Comment by Irrelon** [comment]
If you want to translate the "data-hover" attribute which I am *guessing* is your question, you can tell the plugin to include "data-hover" attributes as described in the readme.md: https://github.com/Irrelon/jquery-lang-js#translating-custom-element-attributes

**Comment by raysefo** [comment]
thank you.
