### ISSUE TITLE
Translate before document redy.

### ISSUE THREAD

**Issue by CapitanPlanet** [Irrelon/jquery-lang-js#92]
Hi 

I want to recive translation before document ready, but json file is not loaded. In "network" tab I see json file is pending.

**Comment by Irrelon** [comment]
Not sure how you would do that. Document won't be ready until after all files required are loaded.

**Comment by Irrelon** [comment]
But if you are trying to achieve translation showing straight away why not put css on the main body to hide the page until loaded and translated, then show the page.

**Comment by CapitanPlanet** [comment]
I need translation while building site... Because i'm using jquerry.steps, and i need labels before i start it. Like this:

var form = $("#wizzard").show();
form.steps({
    labels: {
        current: window.lang.translate('current',),
        pagination: window.lang.translate('pagination',),
        finish: window.lang.translate('Finish',),
    }
,...

Any idea how to aproach this?

**Comment by decadenceqi** [comment]
I have the same problem
