### ISSUE TITLE
Bug:  When appending html with lang-attribute that has empty text nodes but a child element, js throws error 

### ISSUE THREAD

**Issue by drogerie21** [Irrelon/jquery-lang-js#98]
if you do for example this
`$('<div lang="en-US"><textarea></textarea></div>').appendTo($('body'));`
you get an JavaScript error:

![jquery_langjs_bug](https://cloud.githubusercontent.com/assets/1327397/22506349/41707dfc-e880-11e6-8d6e-0fbb0cbb20c0.PNG)

**Comment by charon4ever** [comment]
I have the same question. It seems that the Jquery-lang overrides the "appendTo( )" function of Jquery and whenever i use this function,the browser returns the error like the picture above. I don't know how to solve this problem.
